### ISSUE TITLE
should mosaic::sample() throw an error if subset given as an option?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#396]
Dick DeVeaux noted that mosaic::sample() and mosaic::resample() silently ignore the subset option (but base::sample() throws an error).  See the following reproducible example:

require(mosaic)
require(mosaicData)
favstats(cesd ~ female, data=HELPrct)

dim(resample(HELPrct, subset=female==1))  # no warning
dim(resample(subset(HELPrct, subset=female==1)))

dim(sample(HELPrct, subset=female==1))  # since no warning from mosaic sample
dim(sample(subset(HELPrct, subset=female==1)))

dim(base::sample(HELPrct, subset=female==1))  # base::sample yields warning
dim(base::sample(subset(HELPrct, subset=female==1)))

Dick, just FYI, I tend to encourage my students to subset first (using filter() from dplyr) rather than using the subset option, but your point is well-taken.
Nick

**Comment by rpruim** [comment]
I'm going to close this since (a) it isn't really a bug (and the same thing would happen with any function that has `...` if you send it an argument it doesn't handle) and (b) other things seem more important than this to me.

The only thing that speaks against this is that in the case of `sample()` we are masking an existing function.  I've adopted the general principle that
 * We should not change behavior of functions we mask in situations where they used to work
 * Giving functionality to situations that used to be an error is an acceptable "change of behavior"

Technically, this falls into that latter category, except that we are not providing much functionality in our "change of behavior".
