### ISSUE TITLE
problems with mosaic-resources.Rnw

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#459]
(1) Tintle materials are not included

(2) Lock5 pdf doesn't appear to be correct

(3) Can the specific URL's for the LittleBooks be added in?  Otherwise this feels very cumbersom.

At present, if someone googles "CRAN mosaic" they can just click the URL to download a particular pdf.  

Under the proposed change, someone needs to google "CRAN mosaic", download "mosaic-resources.pdf", click on the github LittleBooks, and navigate through.  This involves many more keystrokes and clicks.  Any ways to minimize this by making each link clickable would be appreciated.

**Comment by rpruim** [comment]
I've converted this to Rmd so it will be included as HTML rather than PDF.  Since this is primarily links to other things, HTML seems like a good format.  Also

 1. Tintle now referenced
 2. I'll look into the Lock5 link -- I'm updating that package currently as well
 3. HTML avoids the PDF download step.  

Regarding which links to use:  The downside of including lots of individual links is that they are always breaking (see item 2).  For the Little Books, I think a link that sits above all of then and treats them like a series isn't too bad since it may also direct people to a different book that is more appropriate.  By having the destination in the github repo where the books live, one would hope that any changes in location will be updated at the same time.

But I will update the link to go directly to the [README](https://github.com/ProjectMOSAIC/LittleBooks/blob/master/README.md) rather than landing at the page that has code on the top and the README at the bottom.

**Comment by nicholasjhorton** [comment]
Not having a direct URL makes it difficult to tweet or share: my experience has been very positive with the status quo which is why I'm pushing for this.  Many people will get stuck and frustrated when they go to a new page which requires additional scanning and more decisions.

But if it's impossible to have a static URL for the pdf, I'll withdraw the request (under protest).

Nick

**Comment by rpruim** [comment]
Do you want to volunteer to keep everything up to date?  My general principal is to keep things that change together close together and DRY (Don't Repeat Yourself).  I don't like having to update the mosaic package when files external to the mosaic package change -- especially since CRAN updates are cumbersome and infrequent.

I'm not sure exactly what you mean by static URL for the pdf -- what does static mean and which PDF?

I think there are two options for PDFs in a github repo:

1. blob:  github now renders the PDF inside a github frame [like this](https://github.com/ProjectMOSAIC/LittleBooks/blob/master/Compendium/MOSAIC-Compendium.pdf)

2. raw: The URL to the "raw" version causes the PDF to be downloaded rather then rendered in the browser.

I've been thinking 1 is better than 2.

**Note:** github's behavior with PDFs had not been constant.  The current behavior seems to have been introduced mid-March 2015.

**Comment by rpruim** [comment]
Do you want to keep the file name the same so that old links still work, even though Compendium is not a good file name for a document called "Student's Guide..."?

**Comment by nicholasjhorton** [comment]
I am happy to help keep things up to date, once we settle on a final naming and location.

I would prefer 2, but have not objections to 1.

Nick

**Comment by znmeb** [comment]
@rpruim Github's renderer doesn't always work: 
![screenshot from 2015-05-18 06-25-05](https://cloud.githubusercontent.com/assets/4938/7681665/cadedf4e-fd26-11e4-8cf6-decfe59b8b6d.png)

It could be a browser issue - I'm pretty bleeding-edge Firefox most of the time.

**Comment by rpruim** [comment]
OK.  At the risk of pleasing none, I'll try to please all.

![image](https://cloud.githubusercontent.com/assets/722231/7692336/8f8b6c7c-fe17-11e4-9896-91ce53ef3767.png)

I'm going to close this here.  `mosaic` can point to the LittleBooks `README` and issues regarding that should go in the LittleBooks repo since that is where we will address them.
