### ISSUE TITLE
possible bug in antiD()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#492]
David Schoenfeld writes:  What am I doing wrong here?
 
> antiD(v*(exp(-b*t)-exp(-(a+b)*t))~t)
function (t, C = 0, v, b, a)
v * 1/(-b) * exp(-b * t) - 1/(-(a + b)) * exp(-(a + b) * t) +
    C
 
 
I think the answer should be
function (t, C = 0, v, b, a)
v *( 1/(-b) * exp(-b * t) - 1/(-(a + b)) * exp(-(a + b) * t)) +
    C
 
Thanks for your help.
 
Note: if I distribute before I anti-differentiate it works fine
 
antiD(v*exp(-b*t)-v*exp(-(a+b)*t)~t)
function (t, C = 0, v, b, a) 
v * 1/(-b) * exp(-b * t) - v * 1/(-(a + b)) * exp(-(a + b) * 
    t) + C
 
Is there a restriction on the depth of the (())?
 
 
 
 
David A. Schoenfeld, Ph.D.
Professor of Medicine, Harvard Medical School
Professor in the Department of Biostatistics, Harvard School of Public Health
50 Staniford Street
Boston, Massachusetts 02114
phone: 617-726-6111
dschoenfeld@partners.org

**Comment by dtkaplan** [comment]
David,

I’m guessing that the function you were anti-differentiating in the first
statement in your email is not the function you were intending to
differentiate.

Keep in mind that the functions are described in R syntax, so your
v(exp(-bt)) is calling a function [image: v()] (undefined in your letter),
and involves a single variable named bt. The resulting anti-derivative is
being given as a numerically calculated function rather than in analytic
form. That’s the best that can be hoped in any circumstance since [image:
v()] is not defined.

If I modify the expression to read v * (exp( -b * t)) the anti-derivative
is the same as the function given in your “I think the answer should be ….”

Here are a few statements implementing

   1. your original function (taken at face value)
   2. my re-implementation taking [image: v] to be a variable
   3. your “should be” function

(2) and (3) give the same result. Evaluating (1) produces an error
since [image:
v()] is not defined.

Regards,
Danny

require(mosaic)

f_from_email <- antiD(v(exp(-bt)-exp(-(a+b)*t))~t)
f_danny <- antiD(v * (exp( -b * t ) - exp(- (a + b) * t)) ~ t)
f_supposed_to_be <- function (t, C = 0, v, b, a)
  v * 1/(-b) * exp(-b * t) - 1/(-(a + b)) * exp(-(a + b) * t) +
  C
# Simple evaluation at one point
vals <- list(t=2, v=8, b=9, a=10)
do.call(f_supposed_to_be, vals)
do.call(f_danny, vals)
do.call(f_from_email, vals)

​
