### ISSUE TITLE
multi-panel dotPlot() point size differs from panel to panel

### ISSUE THREAD

**Issue by swang87** [ProjectMOSAIC/mosaic#500]
In mosaic package v. 0.10.0, it appears that dotPlot() point size is automatically calculated based on some formula that might be related to the number of points in the plot area. The following included example on the help page shows 8 different subpanels, where the point sizes differ from one to the next.

dotPlot( ~ height | voice.part, data = singer, nint = 17,
          endpoints = c(59.5, 76.5), layout = c(2,4), aspect = 1,
          xlab = "Height (inches)")

**Comment by rpruim** [comment]
I've confirmed the "feature" and will have to think about the best way to fix it.  Currently dot sizing is handled within the panel function.  That works well for a single panel plot, but means that multi-panel plots may have different dot sizes.

Some options:

  * move away from automated dot sizing
  * provide an option to make dot sizes fixed
  * write a pre-panel function to do things differently in single panels vs multi-panel plots.  (Allowing auto-sizing that works well but is consistent across panels is probably not that easy since the current method needs to know both the data and the size of the panel viewport, which likely isn't available to the pre-panel function since the panels haven't been created yet.  But we could perhaps turn off the auto-sizing in multiple panel plots.)

**Comment by swang87** [comment]
Randy, 

Thanks for looking into this. Given my very limited understanding of how the dotPlot() function works, I think having an option to fix dot sizes might be easiest in the short run? I understand quite a bit of work goes into figuring out the dot sizes, so picking an appropriate dot size via a "size=" argument (or similar) might take some trial-and-error, but I assume that's the easiest fix to the problem. 

Any solution you choose will be fine. I just wanted to document the find.

**Comment by rpruim** [comment]
Finally getting to this.  I think I have it fixed.

![image](https://cloud.githubusercontent.com/assets/722231/10351870/e8823484-6d19-11e5-9928-839720e3ea1c.png)
