### ISSUE TITLE
Create better quick look at a data frame?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#544]
See discussion here: https://github.com/hadley/dplyr/issues/1514#issuecomment-154398936

**Comment by rpruim** [comment]
Proof of concept:


```r
inspect(Births78)
## 
## categorical variables:  
##   name   class levels missing   n                                  distribution
## 1 wday ordered      7       0 365 Sun (14.5%), Mon (14.2%), Tues (14.2%) ...   
## 
## quantitative variables:  
##        name   class  min   Q1 median   Q3   max mean  sd   n missing
## 1    births integer 7135 8554   9218 9705 10711 9132 818 365       0
## 2 dayofyear integer    1   92    183  274   365  183 106 365       0
## 
## time variables:  
##   name   class      first       last min_diff max_diff missing   n
## 1 date POSIXct 1978-01-01 1978-12-31        1        1       0 365
```

Currently handles the following types of objects:

```r
methods("inspect")
## [1] inspect.character  inspect.data.frame inspect.default    inspect.factor     inspect.logical    inspect.numeric   
## [7] inspect.POSIXt 
```

**Comment by bjornerstedt** [comment]
When writing my function I thought about creating a list of objects instead of putting all in a single data frame. The main advantage with your solution is that it can handle dates better. The main disadvantages as I see it is that output is less concise. Sending the output to knitr markdown is also simpler with one object (especially for beginners in R that I teach).

**Comment by rpruim** [comment]
I'll close this for now.  If someone has a suggestion for improvement we can re-assess.
