### ISSUE TITLE
sloppy use of do() + tally() kills R

### ISSUE THREAD

**Issue by beanumber** [ProjectMOSAIC/mosaic#551]
This code is fine:
```
p <- 0.1
n <- 1040
responses <- c("atheist", "non_atheist")
p_hats <- do(5000) * tally(~resample(responses, size = n, prob = c(p, 1-p)), format = 'proportion')
```
But if I omit the "~" from the formula, I get 5000 warning messages that kill R. 

Now, I understand why the warning is issued, but does it have to be issued 5000 times?? The warning is designed to alert the user to poor syntax, but here the warning is actually causing the crash, since the computation goes through either way.

**Comment by beanumber** [comment]
BTW, how can you make this work?
```
p_hats <- do(50) * 
  resample(responses, size = n, prob = c(p, 1-p)) %>%
  tally(., format = 'proportion')
```
If I'm using `tally()` on a vector, and there is no `data` argument, then why should I need the `~`?

**Comment by rpruim** [comment]
I'm not sure what version of `mosaic` you were using, but `tally()` was refactored recently to make formula-free things work better and there was a missing method for an internal function that was causing some of what you were seeing, at least in the most up-to-date version.

I think that all your code now works in the github version of the package.

Note:  It is safer to use a factor rather than a character vector for what you are doing so that that tally has all levels represented.  In this case, the probability of obtaining a 0 count is pretty low, but on smaller examples, this can be an issue.

As for getting 5000 warning messages, this is a bit tricky since each call to tally is unaware that you are doing 5000 of them.  Warnings would need to be emitted in some different way that kept track of warnings in some global place for the 4999 to know that the first guy already emitted a warning.

In general, one should first do `do(3) * ` to make sure things are working before running 5000.

**Comment by beanumber** [comment]
Could there be a `suppressWarnings` option to `tally()`? And what do you think about the piped example above? Is there a way to have the object in the pipeline become a `formula`?

**Comment by rpruim** [comment]
I think this is good enough.
```r
p_hats <- do(50) * 
  resample(responses, size = n, prob = c(p, 1-p)) %>%
  tally(format = 'proportion')
head(p_hats)
##   atheist non_atheist
## 1  0.1010       0.899
## 2  0.0971       0.903
## 3  0.0990       0.901
## 4  0.1192       0.881
## 5  0.0962       0.904
## 6  0.1019       0.898
```
You should not be piping if the output of one function is not the input to the next.  (Piping is really intended for cases where you have functions that return the same kind of thing as their first argument and everything else is a modifying setting.)

Rather than suppress warnings, it's better to just avoid them.  But perhaps we could have `do()` collect up warnings and simply report that they were there.  I'll have to think about that one.  In general, suppressing errors and warnings comes back to get you later when some error or warning you were not expecting arises but is suppressed and goes unnoticed.

I can't stop you, however, from using `supressWarnings()` to suppress them yourself.

**Comment by rpruim** [comment]
I'm closing this since the immediate problem has been addressed.  Furthermore, we may remove the non-formula version of `tally()` altogether: see #594.
