### ISSUE TITLE
issues with warnings from CIsim()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#569]
> CIsim(100)
Did the interval cover?
  No  Yes 
0.06 0.94 
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In sub("^x$", deparse(x_lazy$expr), res$data.name) :
  argument 'replacement' has length > 1 and only the first element will be used
2: In sub("^x and y$", paste(deparse(x_lazy$expr), "and",  ... :

**Comment by rpruim** [comment]
This is caused by a "feature" of `deparse()` that I think I knew once and had forgotten about:  If the result it long, `deparse()` returns a character vector with multiple shorter strings rather than the whole thing.   My fix is to use only the first component in the labeling of `t.test()` output and to append `...` when there is truncation involved.
