### ISSUE TITLE
seemingly incorrect aggregation by do() in the presence of NA's

### ISSUE THREAD

**Issue by jgscott** [ProjectMOSAIC/mosaic#570]
Here is an example script that produces some strange behavior from do().  I am conjecturing that it relates to what happens when a linear model produces an NA coefficient due to perfect collinearity or missing data inside a do() loop.  

https://gist.github.com/jgscott/ec46b3b8897b6966a20f

**Comment by nicholasjhorton** [comment]
From a statistical standpoint, this is probably a good setting to bootstrap from the residuals. But I agree that this is unfortunate behavior (and that do() should throw an error or warning).

**Comment by rpruim** [comment]
I've created a function for converting a vector into a data frame and I'm wrapping the results of `cull_for_do()` with this function.  This avoids the immediate complaint since now `bind_rows()` can be used to combine things, and `bind_rows()` respects the column names.  This *does not* fix the substantive problems with the example above, and perhaps makes this issue harder to detect.

```r
set.seed(12345)
boot1 = do(1000)*{
    lm(undercount ~ poor + urban + atlanta + republicanlev + equip, data = resample(georgia2000))
}
histogram( ~ numdf, data = boot1)      # how often are we losing degrees of freedom from the model?
histogram( ~ r.squared, data = boot1)  # are all the r.squred values reasonable?
```
![image](https://cloud.githubusercontent.com/assets/722231/13763716/c9b175c4-ea1e-11e5-8906-c729bd21402e.png)

![image](https://cloud.githubusercontent.com/assets/722231/13763710/ba6f58ba-ea1e-11e5-9ae9-7fc0b894544d.png)
