### ISSUE TITLE
add ggplot2 version of pdist() and/or plotDist()?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaic#577]
From an email:

I have been impressed with Mosaic, and am particularly interested in pdist.

I see that you do make use of ggplot in your Mosaic package.  But I think not for pdist?  If I am correct, then are there any plans for that in the future?

Regards

Roger

Roger Stern
Statistical Services Centre
University of Reading, Whiteknights Road, Reading RG6 6FN
Tel: +44 (0) 118 378 6421 (or 8025)
e-mail r.d.stern@reading.ac.uk
web: www.reading.ac.uk/ssc

**Comment by rpruim** [comment]
More interesting might be to great a new geom (`geom_dist()`) that creates a ggplot2 layer containing a plot similar to those produced by `plotDist()`.

**Comment by dtkaplan** [comment]
Yes. I've been thinking about a related issue, since I'm putting together a
formula interface to ggplot2.  Take a look at
https://github.com/dtkaplan/statisticalModeling



On Wed, Mar 16, 2016 at 12:14 PM, Randall Pruim <notifications@github.com>
wrote:

> More interesting might be to great a new geom (geom_dist()) that creates
> a ggplot2 layer containing a plot similar to those produced by plotDist().
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ProjectMOSAIC/mosaic/issues/577#issuecomment-197437055>
>



-- 

...

DeWitt Wallace Professor of Mathematics, Statistics, and Computer Science
Macalester College

**Comment by rpruim** [comment]
I think this is now taken care of by `ggformula::gf_dist()`
