### ISSUE TITLE
Failure with dev lazyeval

### ISSUE THREAD

**Issue by hadley** [ProjectMOSAIC/mosaic#593]
```
checking examples ... ERROR
Running examples in ‘mosaic-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: MSPE
> ### Title: Mean Squared Prediction Error
> ### Aliases: MSPE
> 
> ### ** Examples
> 
> HELP <- HELPrct %>% sample_frac(.3)
> MSPE( gwm( age ~ sex, data = HELP), HELPrct)
[1] 59.70464
> MSPE( gwm( age ~ 1, data = HELP), HELPrct)
[1] 59.4482
> MSPE( gwm( age ~ sex + homeless, data = HELP), HELPrct)
[1] 59.43545
> MSPE( gwm( sex ~ 1, data = HELP), HELPrct)
Error in lazyeval::lazy(x) : Promise has already been forced
Calls: MSPE -> gwm -> data.frame -> tally -> <Anonymous> -> .Call
Execution halted
```

Could you please take a look? I think this is probably throwing an error now instead of returning garbage, but it would be worth a check.

**Comment by rpruim** [comment]
I had fixed this elsewhere (by catching the error message) but forgot that `tally()` doesn't rely on the same underlying code as the other functions where this was an issue.

My solution is a bit less than elegant, the main bit of which is below.  Is there a better way to handle this?

```r
tally <- function(x, ...) {
  # lx <- lazyeval::lazy(x)  # this line is replaced with the tryCatch() below
  lx <- 
    tryCatch(
      lazyeval::lazy(x),
      error = function(e) {
        if (grepl("Promise has already been forced", e$message)) 
          NULL
        else 
          stop(e)
      }
    )
  # remaining code omitted
}
```

@nicholasjhorton , @dtkaplan:  This is another consequence of supporting non-formula first arguments.

**Comment by hadley** [comment]
Youch - what are you trying to do? There's got to be a better way.

**Comment by rpruim** [comment]
We are trying to support all of these forms:
```r
tally(HELPrct$sex)
tally( ~ sex, data = HELPrct)
tally(sex, data = HELPrct)
```
It is the last one that is problematic, because `sex` may or may not exist (and if it does, we want to ignore it and evaluate `sex` within the data frame).  Oh, and we also need to check whether it appears someone is trying to use `dplyr::tally()` and call that instead so that `mosaic` and `dplyr` can coexist nicely.

**Comment by hadley** [comment]
I think trying to support all those forms is impossible to do fully correctly - no matter what you do there is always going to be one edge case that is confusing. For example, what should this do?

```R
age <- ~ sex
tally(age, data = HELPrct)
```

Have you read my latest attempt at spelling out a robust approach at http://rpubs.com/hadley/157957 ?

**Comment by rpruim** [comment]
I haven't read that post, I'll have to take a look.

As for your example above, I know what it *does*, because I take the formula interface to be primary and handle the other case as a fall-back to help when people forget the `~`.  But I agree that the case is somewhere between ambiguous and confusing.

@nicholasjhorton, @dtkaplan:  Any chance this is enough to convince you that it is time to stop supporting the non-formula interface to these?  Now would be the time to do it.

**Comment by rpruim** [comment]
I took a look at the post @hadley mentioned above.  I like some of the new (at least to me) functions in `lazyeval`.  Would love to get rid of supporting the "bare variable" version of our aggregating functions.  I think the result would be cleaner, less likely to harbor hidden bugs, and easier to maintain.

**Comment by nicholasjhorton** [comment]
Randy,

I'm open to the suggestion if we don't hear a chorus of complaints in advance.  We'd want to ensure that we add some discussion of why this was done to the existing vignettes and related resources.

Nick

> On May 26, 2016, at 10:10 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I haven't read that post, I'll have to take a look.
> 
> As for your example above, I know what it does, because I take the formula interface to be primary and handle the other case as a fall-back to help when people forget the ~. But I agree that the case is somewhere between ambiguous and confusing.
> 
> @nicholasjhorton, @dtkaplan: Any chance this is enough to convince you that it is time to stop supporting the non-formula interface to these? Now would be the time to do it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
IMHO not supporting the bare variables actually eases the conversation for students, since it becomes unambiguous that you have to have the `~`. 

On another topic, have you considered changing the order of arguments so that `data` always comes first? The goal would make everything work with `dplyr`. Since most of the `mosaic` functions assume that you are working with a data frame anyway, it seems arbitrary to prefer:
```
f(y ~ x, data)
``` 
over
```
f(data, y ~ x)
```

**Comment by rpruim** [comment]
@beanumber, the current order is not arbitrary and I'm not sure reversing the order makes sense:
 * The paradigm being followed is not `dplyr`, it is `lm()` and `lattice`

 * If you are using `dplyr`, you can use `group_by` and `summarise()` to get similar results

 * reversing the order makes things like `f( y ~ x )` and `mean(rnorm(100))` -- which we **must** support -- more awkward to implement since the `data` argument would have multiple meanings.

 * The first argument of things like `mean()` must be `x` to support things like `mean( na.rm = TRUE, x = foo)`, which while unusual, will work with `base::mean()`.

 * I think you would also want `HELPrct %>% group_by(sex) %>% summarise(mean.age = mean(age))` to work.  So it isn't clear that even from a `dplyr` perspective, we would want the first argument to be a data frame.

 * currently the return type of things like `mean()` is not always a data frame, so it doesn't really fit into the flow of the `dplyr` functions.

But, one could think about doing something different when the first argument is a data frame.  Essentially there would be several options for `x`:

  * a numeric vector
  * a formula (to be interpreted in `data` if it exists and in the enclosing environment if not)
  * a data frame (in which case a formula would be required -- avoiding needing to name it might be a bit tricky given the need to comply with current behavior of the functions being masked) in which case the output format should also be a data frame so it doesn't become a deadend in the piping flow.

I'll give this some more thought, but I'd like to know if there really are sufficiently useful use cases to warrant the extra work of supporting data-frame-first use.

**Comment by rpruim** [comment]
@nicholasjhorton, we would need to give some thought to the transition, but I don't think we should run this up a flagpole and wait to see if there is an outcry against it.  We can't really deprecate this usage in the usual way, especially since this primarily worked as an undocumented feature anyway.  Certainly this would go into the list of changes to the package and be highlighted in any announcements.  The current vignettes don't ever use the bare variable approach, so people didn't learn to do this from those.

Perhaps we could write a short vignette about the formula interface (called *Why the tilde?* perhaps).

**Comment by beanumber** [comment]
@rpruim I get that `mean` doesn't return a data frame, so it won't work in the middle of a pipeline. But there are lots of functions that can be used at the **end** of a pipeline. It would just be easier to write:
```
mtcars %>% 
  mean(mpg ~ cyl)
```
as opposed to:
```
mtcars %>% 
  mean(mpg ~ cyl, data = .)
```
But I also understand that the `group_by` + `summarize` is the `dplyr` way to do this. But one of the reasons I like `mosaic` is that you can use `mean(y ~ x)` without having to type all the `summarize` column definitions. 

On that note, have you had any further thoughts about (https://github.com/hadley/dplyr/issues/1514)? I want to do this:
```
mtcars %>%
  group_by(cyl) %>%
  summarize(favstats(mpg))
```
and get the result of `favstats(mpg ~ cyl, data = mtcars)`. If I have a function that takes a vector and returns a vector (not a scalar), I want to be able to use that with `summarize` without having to type all of the column definitions. [Of course, there is no SQL equivalent.]

I'll leave you with a stupid question that I'm sure that you've thought about many times: why not write a `mean.data.frame()` method that takes a formula argument and returns a `data.frame`?

**Comment by hadley** [comment]
I think it's a little confusing to have a function that works with both vectors and data frames, although I understand that adding more functions is also confusing (along another axis). But I think it'd be better to have `df_mean()` or `col_mean()` or something that took a data frame as a first argument.

**Comment by rpruim** [comment]
Support for 
```r
foo( x, data = somedata)
```
has officially been removed.  This makes the new versions of the functions cleaner (and shorter).  `mosaic` and `lazyeval` are playing nicely together now.
