### ISSUE TITLE
plotDist and bargraph

### ISSUE THREAD

**Issue by kenjimyzk** [ProjectMOSAIC/mosaic#626]
The following chunk does not work.
```
bargraph(~rbinom(1000,10,0.4),type="proportion")
plotDist('binom',10,0.4,add=TRUE)
```
![rplot](https://cloud.githubusercontent.com/assets/3890511/20706531/1a43be3e-b66b-11e6-90b7-1cdc1f759e46.png)

**Comment by rpruim** [comment]
It is "working" as it should, but it is the wrong kind of plot for what you intend to do.  `bargraph()` is for categorical data, so it is converting the numerical values to a factor.  The plot then uses the underlying numerical values to position things.  What you see printed as a 0 is located at position 1.  When you overlay the distribution plot, things are off by one because of this.

The correct way to do this is to use a histogram rather than a bar graph to display the data. 

```r
histogram( ~ rbinom(1000, 10, 0.4), width = 1)
plotDist('binom', 10, 0.4, add=TRUE)
```

![image](https://cloud.githubusercontent.com/assets/722231/20712405/ddc6d9b8-b611-11e6-8416-bf6d030326d7.png)

**Comment by kenjimyzk** [comment]
Thanks!!
