### ISSUE TITLE
add mplot support for ggformula

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#650]
This could be done as a third graphics environment

**Comment by rpruim** [comment]
First draft in progress:

![image](https://user-images.githubusercontent.com/722231/27655622-001f460a-5c14-11e7-88ff-dd43398caf1e.png)

**Comment by rpruim** [comment]
`mplot()` seems to be working fine.  It led to some issues regarding location of things.  I've made `ggformula` a dependency of of `mosaic`.  That means `ggformula` can't have `mosaic` as a dependency, so I had to duplicate a few functions from `mosaic` as (non-exported) functions in `ggformula`.  Eventually I might opt for a `mosaicCore` package that contains functions that are used across multiple packages in the `mosaic` family.  That's probably cleaner, and we might find this happening more as we start building `mosaicModel` or other packages in the family -- or if we pull off parts of `mosaic` into a separate package.

**Comment by dtkaplan** [comment]
I like the mplot() for `ggformula`.

**Comment by rpruim** [comment]
@dtkaplan, have you done much with plug-ins?  Should we convert this to a plug-in?

**Comment by nicholasjhorton** [comment]
I'm really pleased with what you describe about mplot().  Is this pushed to the beta branch?



Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by rpruim** [comment]
Yes.  Give it a try.

You may need to uninstall `mosaic` and `ggformula` before reinstalling. I'm not sure how things work now because I've reversed the direction of their dependency -- `mosaic` now depends on `ggformula`.  Previously `ggformula` imported `mosaic`.  I don't know how that gets handled when updating from github.

This definitely is cause to do a CRAN resubmit of `ggformula` when we update `mosaic`.  I'm thinking next week might be possible, although the holidays may slow things down a bit.

**Comment by rpruim** [comment]
PS.  If you look at the new code, you will see that I have used `glue::glue()` to create some of the strings.  I've been quite liking it for creating strings that are a mix of fixed chunks and computed chunks.  The resulting code is much easier to read than code using `paste()`.  I may convert the `ggplot2` and `lattice` code to that style as well.

**Comment by dtkaplan** [comment]
I've done a little with "addins". (Is that what you have in mind with "plug-ins." Advantages: they can be much more compellingly designed and there's a shiny app behind them that can be used directly. Disadvantages: They only work in RStudio (like manipulate) and they can be a little confusing since they add code to the document being edited. 

I imagine that they could work thus: the writer enters a command like "mtcars" and highlights it. Then select the addin from the addin menu or by keyboard shortcut. This will bring up the mplot-like interface and, when complete, will substitute the highlighted command with the one created by the adding.

**Comment by rpruim** [comment]
That doesn't immediately sound compelling enough to move it to the top of the list.  I'll leave it on the back burner for now, I think.

**Comment by rpruim** [comment]
I'm going to close this.  Open new issues if bugs are found or features need to be added/improved.
