### ISSUE TITLE
mosaic to suggest or depend on ggformula?

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#653]
If there are plans that ggformula would replace lattice as the default graphics environment for mosaic related documentation, then ggformula would seem to need to be added into the mosaic mix (so that library(mosaic) gives full access).

**Comment by nicholasjhorton** [comment]
Is there a final determination of what would make sense here?

**Comment by rpruim** [comment]
`ggformula` is currently a dependency of `mosaic` (as are `lattice` and `ggplot2`).  All three are needed for the current version of `mplot()`.

**Comment by nicholasjhorton** [comment]
Sounds good.  I'm excited about getting an updated mosaic package onto CRAN (but @rpruim already knew that).

**Comment by rpruim** [comment]
CRAN is complaining about the number of dependencies.  I'm doing some work to reduce the number of dependencies.  I currently have `mplot()` checking to see whether `ggformula`, `ggplot2`, and `lattice` are loaded and only offering choices among loaded packages.

Likely `ggformula` will **not** need to be a dependency.  Not sure whether it is worth trying to back out of the `lattice` and `ggplot2` dependencies.

`dplyr` and `Matrix` are tricky because things won't work if they are loaded after `mosaic`.  Making them a dependency makes that impossible.  But we could just emit a message warning the user that the order of loading/attaching these is important.

Thoughts?

**Comment by rpruim** [comment]
Current message:
```
The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.  
If you use the Matrix package, be sure to load it BEFORE loading mosaic.
```

**Comment by nicholasjhorton** [comment]
I would strongly recommend having ggformula as a dependency of mosaic. Otherwise it will be an extra step required to access the basic less volume functionality. 

All the best,

Nick

**Comment by rpruim** [comment]
I'm less sympathetic to that argument, and unnecessary dependencies, in addition to raising flags at CRAN, make maintaining packages more difficult as well.  

Ideally, we should get to a state where one selects `mosaic` and at least one of the three graphics packages (`lattice`, `ggplot2`, `ggformula`) instead of having `mosaic` load all three.  I'm not sure I have the time just now to track down all the places where `ggplot2` and `lattice` are used to minimize the dependency there, so those will likely stay for now.  But if I keep `ggformula` out of the dependency list, we won't build in things that make it harder to separate later.

`Matrix` is unrelated to what we do, but gets loaded by some other packages and can cause issues if this happens after `mosaic` is loaded.  Still, I think it is best to move it out of Depends.  `dplyr` is similar, but it is more directly related to what we are doing.   Still, one could use `mosaic` without `dplyr`...

**Comment by nicholasjhorton** [comment]
I'd prefer to pull out everything that is in tidyverse and include lattice and ggformula. Without ggformula it will be harder to transition. But I'll defer to whatever you decide. 

All the best,

Nick

**Comment by rpruim** [comment]
Hmm.  I guess if we have `ggformula` as a dependency, we will have `ggplot2` as an implicit dependency, but that probably won't raise the same sorts of red flags as having both `ggplot2` and `ggformula` listed.

Let me think about that one.

I think it makes sense to remove `dplyr` if we can and let people load it or `tidyverse` if they are doing wrangling.

**Comment by rpruim** [comment]
I think the main reason for `dplyr` dependence is getting `do()` and `tally()` to play well.  I'll have to think about whether we can get them to play well without the formal dependence (provided `dplyr` is loaded first).

**Comment by nicholasjhorton** [comment]
I'd propose sticking with with dplyr for now (I'd forgotten about the interplay of "mosaic::do()" and "mosaic::tally()").  Swapping from ggplot2 to ggformula is a net zero change, with only mosaicCore new?

**Comment by rpruim** [comment]
Currently seeing how things go with this:
```
Depends:
    R (>= 3.0.0),
    dplyr,
    lattice (>= 0.20-21),
    ggformula,
    mosaicData
```
But trying to avoid any hard-to-remove dependence on `ggformula` and watching for places to lighten the dependence on `ggplot2` and `lattice` as well.  Looks like I'm no longer getting the stern warning message from CRAN checks about the use of `Depends:`

**Comment by rpruim** [comment]
Going forward with this for CRAN release unless I run into a snag.
