### ISSUE TITLE
options for mplot()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#677]
At present, the mplot() function in mosaic_1.1.0 supports the following options for "system=": base, lattice, and ggplot2.  I have two queries:

(1) can another option "ggformula" be added that just maps to "ggplot2"?
(2) can the "ggplot2" option be made the default if the package is installed?

**Comment by rpruim** [comment]
(1) is easy enough.

(2) is silly since mosaic depends on ggformula (at your request, I think).

We could, however, make ggplot2/ggformula the default -- but it would be a change in behavior.

**Comment by nicholasjhorton** [comment]
Thanks again for making mosaic depend on ggformula!  I know that was a PITA.  

I would suggest making the change in behavior at the next release.  Danny, any thoughts?

**Comment by rpruim** [comment]
Should we make gg the default? (also for `mplot()`, for example?)

**Comment by nicholasjhorton** [comment]
My vote would be yes.  Also for plotModel(). And any other graphics add-ons in mosaic.

**Comment by rpruim** [comment]
OK, Now I'm writing silly stuff.  What I meant was also for the `mplot()` stuff that is the old `mPlot()`, ie, the non-interactive plots.

I think I'm fine going in that direction as part of our general push to move from `lattice` to `ggformula`.

BTW, I would like to get a new `mosaic` out the door very soon.  There is something in `mosaic` that is incompatible with the development version of R that is in the works, and I need to deal with that.  (Basically, they are now fixing something in core R that I had fixed in mosaic, but the two fixes don't work together.)

**Comment by rpruim** [comment]
This was already done in the github version of `mosaic`
