### ISSUE TITLE
suggested changes to MinimalRgg vignette

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#707]
@rpruim I'd propose that we tweak the makeFun() example on the MinimalRgg vignette by changing

"l" to "f" or "fun"

I think that the line won't be too long with "fun" rather than "l" and this would be clearer.  But even moving to "f" would be preferable.

<img width="333" alt="screen shot 2018-06-06 at 8 43 02 am" src="https://user-images.githubusercontent.com/530542/41038899-c425ddca-6965-11e8-9644-6157c725fece.png">
https://cran.r-project.org/web/packages/mosaic/vignettes/MinimalRgg.pdf

**Comment by rpruim** [comment]
I think the intention was that l was for "length" since the function returns lengths.  But `length()` is a standard function, so we don't want to mask that.

Some options:
* use `len()` instead of `l()`
* use a different model altogether to avoid the potential name collision

I'm not a fan of using `f()` just because it is a function.

**Comment by nicholasjhorton** [comment]
len() would be my preference of the options you laid out.

I'd also hope that we could remove the MinimalR.pdf vignette from the next release.

**Comment by rpruim** [comment]
I'm fine with getting rid of the lattice-based minimal R.

**Comment by rpruim** [comment]
lattice-based minimal R has been deleted.

**Comment by rpruim** [comment]
Do you like `l.hat()` as a name?

**Comment by rpruim** [comment]
I've made it `l.hat()` for the moment.  Things fit.  For those used to "hat" notation, this will signal that this is an estimate.
