### ISSUE TITLE
`df_stats()` does not (always) produce tidy output

### ISSUE THREAD

**Issue by sebastiansauer** [ProjectMOSAIC/mosaic#731]
I would like to get a "tidy" output of `tally()` (eg., for plotting). `df_stats()` gives tidy output in *some* situations, but apparently not always. I think it would be useful if `df_stats()` would parallel `dplyr::count()`s output.

Consider:

````
 df_stats(~cyl, data = mtcars, tally)
   4 6  8
1 11 7 14
````
not tidy.

In contrast, this is tidy:
````
dplyr::count(mtcars, cyl)
# A tibble: 3 x 2
    cyl     n
  <dbl> <int>
1     4    11
2     6     7
3     8    14
````

`dplyr:count()` output can readily be used for plotting with ggplot; the `tally()` or `df_stats()` output cannot readily used for plotting via ggplot, AFAIK.

Is there are reason I missing for this behavior?

**Comment by rpruim** [comment]
What follows is a bit long -- I used it to think through some things.  In the end, aside from one feature that should probably be labeled a bug, I think `df_stats()` works as it should.

---

Actually, both outputs are tidy, they just have a different idea about what a row should correspond to. 
 But you can easily tell `tally()` that you want a different output format. (The default for `tally()` is to produce a table, not a data frame.)

```{r}
tally(~ cyl, data = mtcars, format = "data.frame")
#>   cyl Freq
#> 1   4   11
#> 2   6    7
#> 3   8   14

```

Note too that `df_stats()` is not really designed to support `tally()`.  From the help:  "Functions used must accept a vector of values and return either a (possibly named) single value, a (possibly named) vector of values, or a data frame with one row."  Using `counts()` would be preferable since it has better labeling and meets the requirements of `df_stats()` documentation, but `tally()` is serviceable.

It might be good to think about how `df_stats()` is designed to work.  The original use case was for computing summaries of numerical values (possibly within groups), by applying some function or functions to a vector of values (for each group, if there are grouping variables).  Each function value becomes one column of output.  For functions that return multiple values (as a vector or 1-row data frame) the results are treated as if each was generated by a separate function.  (So `range()` is treated like separate calls to `max()` and `min()` -- something difficult to do in `dplyr`.)

A categorical  "lead" variable is treated the same way -- it is not a grouping variable, it just determines a vector that will be passed to the function(s).  So if you pass it to `tally()`, you get multiple outputs that become multiple columns.  Since there is no grouping variable, there is just one row.  If you add a grouping variable, you get one row per group, as you would for a quantitative lead variable.

```{r}
# long format designed with covariates in mind
df_stats(cyl ~ am, data = mtcars, counts)
#>   am n_4 n_6 n_8
#> 1  0   3   4  12
#> 2  1   8   3   2
```

`df_stats()` does have an option to produce "long" output rather than "wide" output, but it wasn't designed with a single variable in mind, and doesn't work that well in that use case.  (This should probably be considered a bug and be improved.)  In the meantime, there is also another way to get the desired output, namely 

```r 
df_stats(am ~ cyl, data = mtcars, n = length)
#>   cyl  n
#> 1   4 11
#> 2   6  7
#> 3   8 14
```

More examples below.

``` r
suppressPackageStartupMessages(library(mosaic, quietly = TRUE))

# tell tally() we want a data frame
tally(~ cyl, data = mtcars, format = "data.frame")
#>   cyl Freq
#> 1   4   11
#> 2   6    7
#> 3   8   14

# tally produces a table by default
tally(~ cyl, data = mtcars)
#> cyl
#>  4  6  8 
#> 11  7 14
tally(mtcars$cyl) %>% class()
#> [1] "table"

# counts produces a named vector
counts(mtcars$cyl) 
#> n_4 n_6 n_8 
#>  11   7  14
counts(mtcars$cyl) %>% class()
#> [1] "integer"
# df_stats() 
df_stats(~cyl, data = mtcars, tally)
#>    4 6  8
#> 1 11 7 14
df_stats(~cyl, data = mtcars, counts)
#>   n_4 n_6 n_8
#> 1  11   7  14

df_stats(am ~ cyl, data = mtcars, n = length)
#>   cyl  n
#> 1   4 11
#> 2   6  7
#> 3   8 14

# long format designed with covariates in mind
df_stats(cyl ~ am, data = mtcars, counts)
#>   am n_4 n_6 n_8
#> 1  0   3   4  12
#> 2  1   8   3   2
df_stats(cyl ~ am, data = mtcars, counts, format = "long")
#>   am stat value
#> 1  0  n_4     3
#> 2  1  n_4     8
#> 3  0  n_6     4
#> 4  1  n_6     3
#> 5  0  n_8    12
#> 6  1  n_8     2

# these are pretty ugly -- we should probably handle as a special case or disable
df_stats(~ cyl, data = mtcars, counts)
#>   n_4 n_6 n_8
#> 1  11   7  14
df_stats(~ cyl, data = mtcars, counts, format = "long")
#>   n_4 stat value
#> 1  11  n_6     7
#> 2  11  n_8    14
df_stats(~ mpg, data = mtcars, mean, median, range, format = "long")
#>   mean_mpg        stat value
#> 1 20.09062  median_mpg  19.2
#> 2 20.09062 range_mpg_1  10.4
#> 3 20.09062 range_mpg_2  33.9
```

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
Turns out to be a relatively easy bug fix -- basically one condition check and one more line of code.  This is much better:

```r
df_stats(~ cyl, data = mtcars, counts, format = "long")
##   stat value
## 1  n_4    11
## 2  n_6     7
## 3  n_8    14
```

**Comment by sebastiansauer** [comment]
Thanks, that should work perfectly for me.
