### ISSUE TITLE
xpt:  no default for ncp argument?

### ISSUE THREAD

**Issue by lilbotham** [ProjectMOSAIC/mosaic#736]
We use mosaic in our intro business stats class and love it, but we have a question about xpt in version 1.5.  In that version if students type  `xpt(.67, df = 49)` they get the error "Error in pdist("t", q = q, df = df, ncp = ncp, lower.tail = lower.tail,  : argument "ncp" is missing, with no default".  

In the reference manual for `xpchisq` and `xpbeta` the argument ncp appears to be set to 0 by default, but is there a reason that's not the case for `xpt`?

**Comment by rpruim** [comment]
If you look at the documentation for `pt()` you will see that the default for `ncp` is missing, not 0, and that the two are treated differently:

> Supplying ncp = 0 uses the algorithm for the non-central distribution, which is not the same algorithm used if ncp is omitted. This is to give consistent behaviour in extreme cases with values of ncp very near zero.

When we moved to adding more explicit arguments (rather than relying on ...) we just missed this case.  (`xqt()` is working).  It is an easy fix, we just need to do an explicit check for missing `ncp`.

``` r
suppressPackageStartupMessages(library(mosaic, quietly = TRUE))
xpt(.67, df = 49)
```

![](https://i.imgur.com/zuyHuR5.png)

    #> [1] 0.7469984

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
