### ISSUE TITLE
changes to mosaic::qdata()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaic#753]
For mosaic_1.5.0 qdata returns the following:

```
> mosaic::qdata(rnorm(100), p = c(.05, .95))
     quantile    p
5%  -1.758099 0.05
95%  1.935656 0.95
```

For mosaic_1.6.0 qdata returns the following:

```
> mosaic::qdata(rnorm(100), p = c(.05, .95))
       5%       95% 
-1.406717  1.860344 
```

Is this a known change that I missed?

**Comment by tiffanyjennell** [comment]
This is causing me to fail my homework, and trying to revert the mosaic package causes it to completely disappear off my system. My professor and I had to share screens to see that because of this, it is failing to close and throwing errors, making things into doubles, etc etc. We had to run the same file. I have mosaic 1.7.0, and if you can point me into the right direction to where I can download a zip file of mosaic 1.5.0, I would appreciate it... when I download the .gz I have no clue where to put it, and 
packageurl <- "https://cran.r-project.org/src/contrib/Archive/mosaic/mosaic_0.13.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

for any version pulls errors and deletes mosaic all together (I tried various versions from 0.10.0 to 1.6.0).

**Comment by rpruim** [comment]
Reverting might be tricky since one of the reasons mosaic has been updated is to keep up with changes to other packages, and you probably have newer versions of those as well.

But you can at least attempt to install old versions from github:

```r
# NB: Some things may fail depending on versions of other packages on your system
devtools::install_github("projectMosaic/mosaic", ref = "v1.5.0")
```

You can see a list of releases at https://github.com/ProjectMOSAIC/mosaic/releases

It would be safer to work with the newest version to accomplish your task.
